### ISSUE TITLE
Plotly notifications using serif font

### ISSUE THREAD

**Issue by edg2s** [aatishb/covidtrends#110]
For example when you first zoom in on the graph:
![image](https://user-images.githubusercontent.com/180672/79789414-0bf66a00-8342-11ea-9085-b72fbda772f3.png)

It should probably be placed better.

**Comment by edg2s** [comment]
Here is an upstream issue, but this should probably be overridden downstream too:

https://github.com/plotly/plotly.js/pull/4778

**Comment by aatishb** [comment]
Thanks @edg2s. Do you know if there's a straightforward way to resolve the placement issue as well? Ideally it would be nice if the notification was placed within the graph div.

**Comment by edg2s** [comment]
I looked at the code upstream and the notifier is attached to the <body> and given some absolute offsets putting it on the right of the screen.

The correct way would be to move the notifier in a position:relative container, but the library doesn't appear to allow for that. As the left/right columns are dynamically sized using flexbox it doesn't appear there is a way to cheat it either. The only way to guarantee it appears inside the white area would be to left align it instead, but that may not be any better.
