### ISSUE TITLE
India numbers not matching up with JHU

### ISSUE THREAD

**Issue by dheerajbhaskar** [aatishb/covidtrends#128]
Hi it was mentioned on your website that you rely on John Hopkins University data. However, the value in your website doesn't match up with what's on JHU for India (I've not checked other countries).

Please look at the numbers here
https://coronavirus.jhu.edu/data/mortality

In particular, look under the heading "Cases and mortality by country" for relevant numbers

**Comment by aatishb** [comment]
Hi @dheerajbhaskar, I just checked and am currently seeing 21,370 cases & 681 deaths listed on the website you linked and on Covid Trends.

JHU:
![IndiaJHU](https://user-images.githubusercontent.com/1878638/80120908-a5e42f80-8559-11ea-9f8c-e8fa9382d9c5.png)
Covid Trends:
![indiacases](https://user-images.githubusercontent.com/1878638/80120910-a67cc600-8559-11ea-8a5e-9c9742a07269.png)
![indiadeaths](https://user-images.githubusercontent.com/1878638/80120911-a67cc600-8559-11ea-9a34-3dbc12849a27.png)


Please note that that JHU tracker updates many times a day, whereas Covid Trends updates only when the JHU github data updates, which is once a day.

Please let me know if I'm missing something here.

**Comment by aatishb** [comment]
Closing for now, feel free to reopen if this issue reoccurs.
