### ISSUE TITLE
Address issues identified by Chrome Accessibility Audit

### ISSUE THREAD

**Issue by mustpax** [aatishb/covidtrends#129]
Our current score is 56 so there's room for improvement!

See: [Accessibility report generated by Google Chrome's Accessibility Audit feature](https://github.com/aatishb/covidtrends/files/4523930/covidtrends.accessibility.pdf)

**Comment by rpkoller** [comment]
![Bildschirmfoto 2020-04-27 um 01 36 47](https://user-images.githubusercontent.com/1665422/80322798-aa456c80-8827-11ea-8ca2-129bd3a4ab7e.png)
just a number, there are still many many issues to fix left. but the merged pull request brought it to 100% in chrome lighthouse already.

**Comment by aatishb** [comment]
Closed by #143 #136
