### ISSUE TITLE
Incorrect date for some users

### ISSUE THREAD

**Issue by reaganch** [aatishb/covidtrends#131]
The animation seems to stop at the date 2020-04-21. Any idea why data for the last couple of days aren't showing up?

**Comment by aatishb** [comment]
Hi, I'm not seeing this on my end. Could you try refreshing the page? Also what browser are you using? Thanks.

**Comment by alekhe** [comment]
Same here. Only until 2020-04-22. Tested in Chrome and Edge.
![image](https://user-images.githubusercontent.com/3087551/80241610-18562c00-868e-11ea-9b2f-4c8a6ce1bee9.png)

**Comment by reaganch** [comment]
Just tried on Firefox and Chrome. Clearing browsing cache and refreshing doesn't help. As @alekhe mentioned though, the animation now goes until 2020-04-22.

**Comment by aatishb** [comment]
Thanks @reaganch @alekhe. Are there any errors displayed if you pull up the JavaScript console?

Looks like this could be a bug. I'm at a bit of a loss for what might be causing this, my best guess is some kind of caching issue? Have flagged this so more folks can take a look. Would be good to know how we can reproduce this.

**Comment by reaganch** [comment]
![image](https://user-images.githubusercontent.com/14113814/80259026-bff84c00-86d8-11ea-8097-d1912f58dcee.png)

Is this what you asked for? Sorry, I'm not very familiar with these features of Firefox.

**Comment by aatishb** [comment]
@reaganch yes, that's it, thanks. I don't see any errors on there, other than the usual warnings.

**Comment by rpkoller** [comment]
isn't that an issue with the data source perhaps? if i download https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv and take a look at the first line: 

```
Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,2/1/20,2/2/20,2/3/20,2/4/20,2/5/20,2/6/20,2/7/20,2/8/20,2/9/20,2/10/20,2/11/20,2/12/20,2/13/20,2/14/20,2/15/20,2/16/20,2/17/20,2/18/20,2/19/20,2/20/20,2/21/20,2/22/20,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,4/21/20,4/22/20,4/23/20
```
the data is only available till the 23rd of april now. so maybe it isnt a problem with js and covidtrends and more of an issue with the JHU data set?

**Comment by aatishb** [comment]
To me it sounded like the issue was they were pulling a version of the data that was about a day older than the most recent. Also received a message from another person running into what seems to be the same issue.

**Comment by rpkoller** [comment]
Since the last few days data was a bit behind from Johns Hopkins I've rechecked today and: 

![Bildschirmfoto 2020-04-28 um 10 40 57](https://user-images.githubusercontent.com/1665422/80466475-e61e2600-893c-11ea-9347-aee6a48e0fe4.png)

So the data set has numbers for the 27th available as well already but Safari 13.1 on MacOS 10.13.6 shows only until the 26th. So reproducible for me as well now (never noticed before always thought data coming in with just a bit of delay). :/ Since it is one day off maybe some sort of array miscount?

**Comment by aatishb** [comment]
Hmm.. interesting. Thanks for sharing this. I doubt it's an array miscount as only some users are seeing this, so I suspect that it may be a caching issue instead.

**Comment by rpkoller** [comment]
@aatishb hmmm i guess it is not necessary or entirely a caching issue. i've rechecked the curve for germany right now: 

![Bildschirmfoto 2020-05-01 um 03 35 40](https://user-images.githubusercontent.com/1665422/80774353-17753c80-8b5d-11ea-8275-1090ddf5e412.png)

now i went to the github repo of johns hopkins university: 
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

scrolled to the latest value in the row for germany: 

![Bildschirmfoto 2020-05-01 um 03 35 54](https://user-images.githubusercontent.com/1665422/80774398-35db3800-8b5d-11ea-8523-d96d57de1e33.png)

and then went up checking what the latest rows header is: 

![Bildschirmfoto 2020-05-01 um 03 36 00](https://user-images.githubusercontent.com/1665422/80774419-44c1ea80-8b5d-11ea-907d-1d3c2babe67b.png)

so in the pane the correct and latest available value in the csv file is shown with 161539. in the csv file that is the value for the 29th of april. but covidtrends label show 28th of april as the latest date. but on that date the value in the csv would be the previous and that is 159912

same e.g. for brazil: 
![Bildschirmfoto 2020-05-01 um 03 42 20](https://user-images.githubusercontent.com/1665422/80774623-d0d41200-8b5d-11ea-8a6d-883f13688c8f.png)
![Bildschirmfoto 2020-05-01 um 03 42 29](https://user-images.githubusercontent.com/1665422/80774631-d4679900-8b5d-11ea-8a21-2115a943cc27.png)

**Comment by aatishb** [comment]
@rpkoller Thanks for this. Great that you are able to reproduce this. 

Could you try adding a random string to the urlPostFix variable i.e. append some random characters to the end of line 323 [here](https://github.com/aatishb/covidtrends/pull/155/files#).

so e.g. change
`       let urlPostFix = '?' + Math.floor(Date.now() / (8 * 60 * 60 * 1000));`
to
`       let urlPostFix = '?' + Math.floor(Date.now() / (8 * 60 * 60 * 1000)) + 'randomCharsHere';`

Since the urlpostfix only updates every 8 hours, I'm wondering if perhaps you are pulling a previous cache from before the recent data update?

**Comment by aatishb** [comment]
Also, when you load this URL, what is the last date you current see in the header?

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

This is the URL we pull data from. I'm seeing up to 4/29 currently.

**Comment by rpkoller** [comment]
@aatishb you mean run the site locally and adjust the string for pulling the csv?

**Comment by aatishb** [comment]
Sorry @rpkoller, I'm re-reading your comment more carefully. I had missed the main point and thought you were running it locally. So the data is correct but the date is wrong. In that case I agree this is probably not a caching issue.

Can you confirm that you see up to 4/29 on [this link](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)?

**Comment by rpkoller** [comment]
![Bildschirmfoto 2020-05-01 um 04 07 46](https://user-images.githubusercontent.com/1665422/80775942-573e2300-8b61-11ea-92b4-ff3e2a9516a8.png)

**Comment by aatishb** [comment]
Thanks. For the sake of comparison, here's what I see. 

![Screen Shot 2020-04-30 at 10 08 20 PM](https://user-images.githubusercontent.com/1878638/80776034-4b396d80-8b2f-11ea-991c-a189120061d8.png)
![Screen Shot 2020-04-30 at 10 08 55 PM](https://user-images.githubusercontent.com/1878638/80776035-4b396d80-8b2f-11ea-9901-422247e39236.png)

Hmm.. this is making me wonder if this might be a time zone issue.

**Comment by rpkoller** [comment]
uhhhhhh WOW that is indeed wild... also tricky to figure out the root of the problem initially... but why time zones? i thought the labels just refer to the dates from the row headers?

**Comment by aatishb** [comment]
@rpkoller thanks for your help in debugging this. Time zones is just a guess based on the fact that this issue has shown up for people in other time zones (Europe, India). I will investigate further.

The dates are passed through the [formatDate function](https://github.com/aatishb/covidtrends/blob/master/vue-definitions.js#L472-L479 ) to internationalize the date format to yyyy-mm-dd.

So that might be the first place for us to investigate. cc @edg2s

I'll investigate further but the soonest I can take a close look is over the weekend.

**Comment by rpkoller** [comment]
ahhhhhh didn't know that the data is getting passed through a formatDate function. Just thought the content of the csv would be simply parsed building the curves and their labels. that way your suspicion might be a possibility. maybe i'll take a look tomorrow as well. but now it is sleep-time. 4:30 am already ;)

**Comment by aatishb** [comment]
Possibly related: 
https://stackoverflow.com/questions/2488313/javascripts-getdate-returns-wrong-date
https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off

**Comment by aatishb** [comment]
I just tried typing `new Date("2020-04-29")` into my browser console, and received the output
`Date Tue Apr 28 2020 20:00:00 GMT-0400 (Eastern Daylight Time)
`

Note the different date!

And `new Date(2020,4,29)` gives `Date Fri May 29 2020 00:00:00 GMT-0400 (Eastern Daylight Time)` which is the right date but unexpected month -- it looks like months are zero indexed.

Confusing!

**Comment by rpkoller** [comment]
hahaha see that was the offset i meant. a value one off is always an indication of an array miscount. like the starting with either zero or one ;) and indeed confusing as hell. timezones is a head scratcher on its own already ;)))

**Comment by rpkoller** [comment]
![Bildschirmfoto 2020-05-01 um 05 29 28](https://user-images.githubusercontent.com/1665422/80779728-cb31f880-8b6c-11ea-8766-25fbbe7e58d6.png)
![Bildschirmfoto 2020-05-01 um 05 29 00](https://user-images.githubusercontent.com/1665422/80779733-cf5e1600-8b6c-11ea-85f2-55125225ddf2.png)

**Comment by edg2s** [comment]
My original patch didn't use toISOString, but that always outputs UTC. The easiest fix would be to use Date.UTC:
```js
new Date(2020,04,01).toISOString().slice(0,10)
> "2020-04-30"
new Date(Date.UTC(2020,04,01)).toISOString().slice(0,10)
> "2020-05-01"
```

**Comment by aatishb** [comment]
Fixed!
@all-contributors add @reaganch for bug

**Comment by reaganch** [comment]
Woot! Glad you were able to get to the bottom of this.
