### ISSUE TITLE
Puerto Rico data not displaying properly 

### ISSUE THREAD

**Issue by Megamaxmax** [aatishb/covidtrends#134]
Found an interesting error, starting on the 21st Puerto Rico's New Confirmed Cases dips waaaaaay off the graph. On the linear graph it says there are -128 cases, but on the logarithmic graph it sinks down to the point where I could not find the end of it. Even after reaching -e+40.

**Comment by aatishb** [comment]
Thanks for pointing this out @Megamaxmax. I believe this is a duplicate of #114.

**Comment by Megamaxmax** [comment]
So it is, sorry about that. I'll close this one out then.
