### ISSUE TITLE
Anything happened in China? The spike in reported deaths seems off

### ISSUE THREAD

**Issue by rpkoller** [aatishb/covidtrends#135]
![Bildschirmfoto 2020-04-24 um 22 50 47](https://user-images.githubusercontent.com/1665422/80255940-30be4a80-867e-11ea-9238-142a39ead3a0.png)
That sudden spike in death looks strange and unnatural and the curve looks odd getting to the new numbers. Is the data source still valid or got it corrupted?

**Comment by aatishb** [comment]
They revised the death toll for Wuhan / Hubei by ~1300 deaths last week. This has been widely reported. see e.g. https://www.reuters.com/article/us-health-coronavirus-china-toll-idUSKBN21Z052

**Comment by rpkoller** [comment]
i read about it. but would have expected they would have changed the daily recordings of previous days and sorted it to the according days instead of counting it to the present day (22.4.). ;) ok that way it makes sense again. thanks for clarification :)
