### ISSUE TITLE
Nova Scotia is missing a label

### ISSUE THREAD

**Issue by rpkoller** [aatishb/covidtrends#139]
![Bildschirmfoto 2020-04-25 um 19 32 53](https://user-images.githubusercontent.com/1665422/80286419-a6342480-872b-11ea-96f8-d07e24b310a3.png)

Seetings:
Confirmed cases 
Canada 
Logarithmic Scale

-> if you deselect all and then choose Nova Scotia you get the representation seen in the screenshot

**Comment by rpkoller** [comment]
...the odd thing is in the `.csv` file Nova Scotia is listed.

**Comment by aatishb** [comment]
Interesting. It appears to be a data issue. For some reason the most recent data for Nova Scotia is -1.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

The label / pink dot is assigned to the most recent data point, which in this case we end up filtering out. I doubt we need to change this behavior, to me it seems more like a temporary data issue.

**Comment by rpkoller** [comment]
oh interesting, when i've noticed that behavior, when i've checked the csv file i havent spotted any -1 at the end of nova scotias data. but that way it more comprehensible. then i agree it will be only a temporary issue. thanks!
