### ISSUE TITLE
Where do the reports of the Lighthouse reports actually go? 

### ISSUE THREAD

**Issue by rpkoller** [aatishb/covidtrends#180]
![Bildschirmfoto 2020-05-11 um 01 46 31](https://user-images.githubusercontent.com/1665422/81513512-565b7d00-9329-11ea-9807-ec1d013e08df.png)
are the paths correctly set so the reports are accessible for the tests?

**Comment by aatishb** [comment]
It's somewhat well hidden (would be nice if this could be more easily visible). 

When you see the tests on a pull request, click Show All Checks and then click Details next to lighthouse audit.

![Screen Shot 2020-05-10 at 9 41 01 PM](https://user-images.githubusercontent.com/1878638/81516775-15eb0780-9307-11ea-9262-8145e67a87fc.png)

Then, on the top right, under Artifacts, you can download the link to the report.

![Screen Shot 2020-05-10 at 9 40 37 PM](https://user-images.githubusercontent.com/1878638/81516807-30bd7c00-9307-11ea-9b11-05c578dd8a53.png)

Keep in mind that the performance score seems a bit variable so we needn't be overly concerned with small changes to the performance numbers.

**Comment by rpkoller** [comment]
ahhh indeed well hidden ;)))) i haven't noticed that. the other lighthouse action by paul irish at.al. had a bit more accessible reach for the reports. but well as long as i know where to look now all is fine ;) 

and well the report affirms one observation i had before the script evaluation time for js in general and the js execution time for `vue-defenitions.js` in particular is off the charts with 24s and 22s. that might need some investigation.

**Comment by aatishb** [comment]
Perhaps we can open a separate issue for improving our performance score. 

However I want to urge caution that the lighthouse performance test score appears highly variable (in my experience, the score can vary from 18 to 36 without meaningful performance code changes). So I think we should either use a more reliable score to test against than the one that lighthouse provides, or we should average a large number of lighthouse scores.

ok to close this issue?

**Comment by rpkoller** [comment]
lighthouse performance tests arent a benchmark for me usually. just an indicator. at least those metrics of script evaluation and execution time. when i test i use webpagetest.org and i dont do a single run but 6 to 9 consecutive ones. that way you get a rough idea. and i use a motorola g4 with a slow 3g network. that is mirroring the average visitor best. good you have to consider that you have that timeline animation at the beginning which is slow anyway. ;) so one part webpagetest the other part chrome devtools. 

and yep i agree lets open up another issue. just wanted to point out that a basic need and caution in that regard is necessary. :)

**Comment by aatishb** [comment]
Thanks @rpkoller!
