### ISSUE TITLE
updating the URL for sharing?

### ISSUE THREAD

**Issue by Pomax** [aatishb/covidtrends#183]
It would be nice if the `window.location.search` got updated (or a `history.replaceState` got affected) when selecting things like "Canada" or "reported deaths" + "linear scale", so that you can share the same view with people without having to tell them which options to then click/select before they'll see the same thing.

(mostly to obviate the need for the "shareable link" button)

**Comment by rpkoller** [comment]
https://github.com/aatishb/covidtrends/pull/182

**Comment by Pomax** [comment]
closing as duplicate of https://github.com/aatishb/covidtrends/pull/179

**Comment by rpkoller** [comment]
@Pomax sorry for the brief answer before! i was cooking dinner aside and was kind in a rush but just saw your question coming in and had read the according pull request few minutes before so i thought just quickly answer and point you there showing that things are already in works :)
