### ISSUE TITLE
Mainland China data should have Hong Kong and Macau deconsolidated

### ISSUE THREAD

**Issue by jonstanley** [aatishb/covidtrends#2]
As both Hong Kong and Macau are separate legal jurisdictions and travel between them and mainland China require passports. Covid19 cases should not be consolidated as one for the three territories. China should be mainland-only (exclude HK & MO) with Hong Kong and Macau being their own clickable entities.

**Comment by memiux** [comment]
The source data is fetched from https://github.com/CSSEGISandData/COVID-19

And it seems that this kind of issues has been already reported:
https://github.com/CSSEGISandData/COVID-19/issues/516
https://github.com/CSSEGISandData/COVID-19/issues/530
https://github.com/CSSEGISandData/COVID-19/issues/533
https://github.com/CSSEGISandData/COVID-19/issues/609

**Comment by jonstanley** [comment]
> The source data is fetched from https://github.com/CSSEGISandData/COVID-19
> 
> And it seems that this kind of issues has been already reported:
> [CSSEGISandData/COVID-19#516](https://github.com/CSSEGISandData/COVID-19/issues/516)
> [CSSEGISandData/COVID-19#530](https://github.com/CSSEGISandData/COVID-19/issues/530)
> [CSSEGISandData/COVID-19#533](https://github.com/CSSEGISandData/COVID-19/issues/533)
> [CSSEGISandData/COVID-19#609](https://github.com/CSSEGISandData/COVID-19/issues/609)

Yes, noticed this as an upstream problem and they were also screwing up Taiwan's naming/data... just hoped a data-parsing case could be added to @aatishb's visualiser regardless of upstream format for "China"...

**Comment by sjmackenzie** [comment]
Could we get a resolution to this problem. It'd be really wonderful having a non-political dataset and representation. I've tried very hard to contact senior Whiting School of Engineering staff to solve this problem. It seems like this problem is *not* going away.

**Comment by sjmackenzie** [comment]
As per [Wikipedia](https://en.wikipedia.org/wiki/Hong_Kong#Government_and_politics): 

`
Hong Kong is a special administrative region of China, with executive, legislative, and judicial powers devolved from the national government. The Sino-British Joint Declaration provided for economic and administrative continuity through the transfer of sovereignty, resulting in an executive-led governing system largely inherited from the territory's history as a British colony. Under these terms and the "one country, two systems" principle, the Basic Law of Hong Kong is the regional constitution.
`

`devolved from the national government`, means Hong Kong shouldn't be [categorized as part of China](https://aatishb.com/covidtrends/?region=China&location=Hong+Kong) 

If you could please apply a correction at the step between Johns Hopkins data extraction and displaying on your website?

**Comment by aatishb** [comment]
Sounds reasonable, and it seems like this should be technically feasible without too much refactoring. 

Following @jonstanley's suggestion, let's try to pull out Hong Kong and Macau to country level. We already have some code to relabel countries, and can relabel China to Mainland China to clarify this change.

One thing to be careful about (I can add this in to the PR later): for the purposes of the createURL / loadURL features (create shareable link button) let's leave china as is so we don't break existing custom links.

**Comment by aatishb** [comment]
Another thing to be careful about: JHU have been changing how they organize their data fairly often, so it would be a good idea for the new fix not to break in the event that JHU re-categorizes Hong Kong & Macau further down the road.

**Comment by neon-ninja** [comment]
If it helps, I solved this in my fork with only one line of code:

https://github.com/UoA-eResearch/covidtrends/commit/cd8686ee5173150496bf5586b356257fdc4485a8

**Comment by aatishb** [comment]
@neon-ninja neat, thanks for sharing! super helpful. ok if we incorporate your code on this? happy to add you as a contributor. or feel free to put in a pull request and we can build on it.

**Comment by aatishb** [comment]
@neon-ninja I went ahead and put in a PR building on your solution. (Will add you as a code contributor once it's merged.)

**Comment by lionello** [comment]
I made #51 for the same reason: to be able to compare individual provinces/states and countries.

**Comment by aatishb** [comment]
Thanks all. This is now live. You're welcome to add yourselves as contributors by tagging @all-contributors. https://allcontributors.org/docs/en/bot/usage
