### ISSUE TITLE
Running Vue in development mode

### ISSUE THREAD

**Issue by NeverFearTheasHere** [aatishb/covidtrends#27]
Are you aware that Vue.js is running in development mode on https://aatishb.com/covidtrends/ ?

There's lots more info about this here: https://vuejs.org/v2/guide/deployment.html

Your graphing tool is a really great resource, thank you!

**Comment by aatishb** [comment]
Thanks for pointing this out, good call!

**Comment by aatishb** [comment]
We should fix this. We'll need to add the [vue.min.js](https://vuejs.org/v2/guide/installation.html#Direct-lt-script-gt-Include) file into the libraries folder and link appropriately. Let's leave the current vue file in there too. That way when developing, we can just remove the .min part to switch to development mode.

You're welcome to put in a PR for this if you like.

**Comment by aatishb** [comment]
@all-contributors add @NeverFearTheasHere for bug
