### ISSUE TITLE
Scale data per-capita

### ISSUE THREAD

**Issue by jwosty** [aatishb/covidtrends#4]
I would love to have an option to see the data scaled per-capita instead of absolute numbers. This shouldn't change the trends (right?), but it would give a better sense of relative scale between countries. For example, the US is currently beating Italy (as of 3/27/2020) on an absolute scale -- with the US at ~70k weekly and ~83k total and Italy at ~40k weekly and ~80k total). However if you adjust for the populations of the countries, you see these figures (trivial math -- try it yourself):

US total: 25.6 cases per 100,000 people
US weekly: 21.4 cases per 100,000 people
Italy total: 133.2 cases per 100,000 people
Italy weekly: 65.4 cases per 100,000 people

This paints an interesting picture. I suppose it shows that right now, even though the US is starting to beat Italy in terms of absolute quantities, Italy is still, for the moment, being hit proportionally harder. I wonder if/where the point could be that the US passes Italy up in that metric.

**Comment by daald** [comment]
it's hard to find a duplicate in a list of 4 issues ;) #1

**Comment by jwosty** [comment]
Silly me. Thank you for pointing that out
