### ISSUE TITLE
Missing countries in reported dataset

### ISSUE THREAD

**Issue by martinszy** [aatishb/covidtrends#47]
When I select "Reported deaths" there's much less countries than for the "Confirmed cases" dataset, even countries with more than 5 deaths now. 

Would you please update countries the list? Thanks.

**Comment by aatishb** [comment]
Hi, it should show all countries that have at least 50 deaths and one week of data. Please let us know if there's a specific country you have in mind that should be in the list but isn't. Thanks.

**Comment by martinszy** [comment]
Mexico is at 50 as of today, and it's not there. Also, I don't think it's clear from the interface that 50 is the minimum.
![Captura de pantalla de 2020-04-03 01-38-16](https://user-images.githubusercontent.com/997732/78335984-dc76ed80-754b-11ea-9638-efaf2e334be8.png)

That 5 could maybe be changed into a boldened 50, so there's no confusion.

**Comment by aatishb** [comment]
Hi. Thanks for clarifying. We are pulling data from JHU time series, which is updated once a day. [As of April 2](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) deaths in Mexico were below 50. It should show up on our graph whenever the daily update from JHU exceeds 50.

We do state below the red Countries heading that we are listing those with at least 50 cases/deaths. 

Will think about the scale issue & whether we need to clarify. Thanks. 

Am closing this for now as I don't think we are missing countries, feel free to reopen if need be.
