### ISSUE TITLE
Add breakdown by state (USA, Canada, etc)

### ISSUE THREAD

**Issue by davydhong** [aatishb/covidtrends#5]
each states should have different curves

**Comment by gfk** [comment]
Canadian provinces data is included in the John Hopkins data, so that shouldn't be too hard to add.

**Comment by fchu** [comment]
FWIW, @nytimes has data in the US per state and per county: https://github.com/nytimes/covid-19-data

**Comment by mr-ransel** [comment]
Alternatively I would recommend using something like this: https://coronadatascraper.com/#timeseries-jhu.csv

It looks much like the johns hopkins dataset, but include county, state (in the US and some other countries) and country level information for most of the world and is updated in a programatic way.

**Comment by aatishb** [comment]
Hmm.. at the moment I'm a bit wary of including third party scrapers as I'm concerned about data accuracy & reliability. For now I'd prefer to keep the list of data sources as narrowly defined as possible, ideally JHU and NYT if we can get those formats to work together. That way if there's a problem with the data down the road, we know where to look.

**Comment by rachellevanger** [comment]
JHU also tracks US numbers at the county level. I think this will be really interesting to see, as the spread of the virus will travel county-by-county and hit various parts of each state at different times. This can later be cross-referenced with local mandates for shelter-in-place, etc.

**Comment by VincentSC** [comment]
While at it, could you also combine EU? And going further, also per continent? So that would result in a tree. Europe goes through borders (Russia and Turkey), so hopefully not a politically sensitive thing.
