### ISSUE TITLE
Browser Cache Reload Issues

### ISSUE THREAD

**Issue by aatishb** [aatishb/covidtrends#61]
Been getting some emails and messages that when we push an update, it breaks the site on Microsoft Edge. The issue seems to be that Edge is holding on to the old cache. Is there any way we can force the browser to reset cache after pushing a change?

Here's what Edge users see when this happens, so this is not a graceful break.

![screenshot,COVID_trends,Edge_private_window](https://user-images.githubusercontent.com/1878638/78505205-e2cdbb00-773f-11ea-9b39-46759271c73d.png)

**Comment by arjo129** [comment]
There seem to be several solutions.
https://stackoverflow.com/questions/1922910/force-browser-to-clear-cache

**Comment by aatishb** [comment]
changing title as it seems this affects other browsers as well

**Comment by edg2s** [comment]
+1 to adding a query string version number. This is used by Wikipedia, for example.

It will however require a version number increment commit each time you deploy a new asset.

`<script src="foo.js?27">`

**Comment by arjo129** [comment]
We might want to have some form of automation for this?

**Comment by aatishb** [comment]
Happy to do it manually as well if it's simpler. Right now it's nice (at least from my perspective) that we don't need to compile or build anything.

So if I understand this correctly, all that's need is to add a ?number to the end of all the updated files linked in index.html? i.e. linked javascript and css files? Let's try to do this on future updates.

**Comment by aatishb** [comment]
Closing. Adopting the approach were we add a ?number to updated linked .css & .js files
