### ISSUE TITLE
Date format ambiguous

### ISSUE THREAD

**Issue by eliotb** [aatishb/covidtrends#64]
A small  nit #/#/## is ambiguous as to which is month and which is day. 
Less ambiguous e.g. "4 Apr 2020? 
Or a localized format (not sure if this is possible)?

As the slider moves, the day number becomes clear, but still requires a mental switch for non USA people.

**Comment by aatishb** [comment]
Thanks for pointing this out. This is in the works with #22 / #28.

**Comment by aatishb** [comment]
Closing as this is now live.

**Comment by aatishb** [comment]
Apologies, looks like I closed this prematurely. Ran into a bug that needs fixing: https://github.com/aatishb/covidtrends/pull/67

**Comment by aatishb** [comment]
Merged.
