### ISSUE TITLE
Enhancement Suggestion: Replace X-axis with total new cases in 8 weeks

### ISSUE THREAD

**Issue by danslee** [aatishb/covidtrends#7]
As the pandemic goes on, the earliest numbers of cases have less and less relevance to the current pool of infected and the spread of the disease. I think it makes sense to replace the current lifetime total of the X-axis with a moving window of 8 weeks. Perhaps 12 weeks to be even more conservative. Thanks for the great visualization and code!

**Comment by aatishb** [comment]
I think this makes a lot of sense from a technical perspective, and is easy to implement, but I'm concerned it would also be confusing.

Here's what I also mentioned in #29:

This change would cause the trajectories on the graph to move forwards and backwards (i.e. to traverse a loop. The end of the epidemic is the same point as the beginning). This could be visually confusing or distracting for most people and difficult to quickly interpret / understand.

Personally I would love to see these kinds of graphs myself, but I'm not sure it's right for this branch as it seems a bit less accessible.

**Comment by danslee** [comment]
That sounds reasonable, I’ll figure out a way to make this thought into a separate feature request. Thanks!
