### ISSUE TITLE
Add lines for number of days for doubling the cases

### ISSUE THREAD

**Issue by mandarpotdar** [aatishb/covidtrends#82]
In this graph (https://aatishb.com/covidtrends/), can you add lines which indicate how many days it takes to double the cases? For eg, the line US is following indicates doubling every 5-6 days. A parallel line below it would indicate, say, 10 day doubling.
Regards,
Mandar

**Comment by aatishb** [comment]
Thanks for suggesting this. I agree that this is an important addition to help people understand the graph. I'm thinking we add trend lines for doubling every 2 days, 5 days, 10 days -- although we can adjust these by eye to see what doubling times work best. The goal would be to capture the variability as well as the 'global best fit' in the data.

**Comment by mandarpotdar** [comment]
Thanks. Found an example here: https://80000hours.org/2020/04/good-news-about-covid-19/?fbclid=IwAR0onP0lA2tos8QoOydWWflIL4WL08A0eBj-ZnttKpE9gwLgfASWYwb_ENo

**Comment by HelgeStenstrom** [comment]
How can you add a trend line for doubling every n days, if there is no time axis?

**Comment by aatishb** [comment]
Growth that doubles every n days is a specific exponential growth curve (the doubling time is related to the exponential growth rate). In the log-log graph, exponential growth curves are displayed as diagonal lines with the same slope, but shifted up or down depending on their growth rate (i.e. doubling time). So basically these trend lines on the log-log curve would all have the same slope, but shifted up and down. On the linear curve the trend lines would have different slopes, like in the image above.
