### ISSUE TITLE
Ontario Canada data is falling behind? In sync with Quebec?

### ISSUE THREAD

**Issue by MilesFaulkner1** [aatishb/covidtrends#87]
Every day Ontario Gov't publishes at 10.30 am their stats in detail.  As of yesterday 9/4 there were 6237 cases open.  Your chart shows 5276 but I also note the chart title says 08/4.  Then again I look at Quebec data same chart and we we see 10031. According to the Quebec Govt web site as of 6pm April 8th they had 10,912 cases.  Since these are publically available data sets - I am wondering whether your data is behind for ontario and then even so whether its accurate for Quebec?

**Comment by exclipy** [comment]
Seems to be working for me: 
![image](https://user-images.githubusercontent.com/508799/79051566-e7dab080-7bfe-11ea-8c93-107a39e3ea57.png)

**Comment by exclipy** [comment]
The data comes from [JHU](https://github.com/CSSEGISandData/COVID-19) so there will be a lag between the government published figures and these ones.

**Comment by MilesFaulkner1** [comment]
I just checked Ontario data is a full day behind. 

Eg the official count is 6648 today for yesterday whereas your model is showing 6247. Even though it states the 10th but its actually the 9th 

 

There was something weird about Quebec also but I can’t remember exactly. 

Rgds Miles

**Comment by aatishb** [comment]
Closing this for now as it seems like a data issue and not something we can resolve on our end.
