### ISSUE TITLE
Add a 1:1 reference line to the log-log graphs

### ISSUE THREAD

**Issue by archiewood** [aatishb/covidtrends#91]
Given the axes, logarithmic growth is characterised by a straight line with gradient 1. 

Whilst you can almost see this from the chart, it would be helpful to have this y=x line as a reference - so you can see how far a country has deviated below logarithmic growth.

I should say, I think this is an absolutely excellent viz. The best I have seen out there for measuring progress

**Comment by aatishb** [comment]
Hi, this is related to #82, which is a priority. Correct me if I'm wrong, but I think a y=x line would correspond to a doubling time of e days. It may be clearer to illustrate trend lines for different integer doubling times (e.g. 2 days, 5 days, 10 days).

**Comment by archiewood** [comment]
Missed that, apologies - do close /merge this 

(I think if you are using a base 10 log rather than natural ln, then a y=x line would a doubling time of 1 unit of time (as defined by your y axis rate of change denominator. Ie 1 week:


From the [SI compartmental model](https://idmod.org/docs/general/model-si.html), which should be a good approximation in early stages:

dI/dt = beta*S*I/N, [beta = 1/doubling time]

log (dI/dt) = log(I) +log(beta*S/N)

in limit I << N (many less infected than total population), S/N --> 1

log(dI/dt) =log(I) + log(beta)

which is your plot, with intercept of log(beta)

for log(beta)=0, beta =1, 
ie doubling time of 1 time unit.)

**Comment by aatishb** [comment]
Thanks for the clarification, this is helpful!

**Comment by aatishb** [comment]
@all-contributors add @archiewood for ideas
