### ISSUE TITLE
Data inconsistency for France

### ISSUE THREAD

**Issue by Rattle22** [aatishb/covidtrends#93]
Somehow, the current Data Point for France has less total cases than before. This is visible as a backward bend in the graph connected over time.

**Comment by aatishb** [comment]
Thanks for pointing this out. Looks like this is currently a known issue with the JHU data source: https://github.com/CSSEGISandData/COVID-19/issues?q=is%3Aissue+is%3Aopen+france

Not much we can do until they fix this. (We could look for a separate data source, but I'd rather wait for them to fix this.) In the past, they've often gone back and retroactively fixed some mistakes like this, so let's hope that happens. They clearly have a lot on their plate, so it may take a few days. Let's wait and watch.

**Comment by aatishb** [comment]
It looks like this might have been fixed now?

**Comment by Rattle22** [comment]
Yep, looks good ^^
