### ISSUE TITLE
A few issues with the markup of the index.html

### ISSUE THREAD

**Issue by rpkoller** [aatishb/covidtrends#98]
Hi I've taken a brief first look at the markup and noticed a few issues and low hanging fruits in regards of html5 validity. I could create a quick pull request if you want to. The minor details I've noticed: 

- remove the two meta content lines 
```
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
```
and replace that with the best practice of 

```
<meta charset="utf-8">
```
and position it right before the title element (see https://htmlhead.dev)
- move the twitter card as well as the open graph meta data to the `head` element
- remove the two closing tags of `img` elements for the two logos

best regards ralf

**Comment by aatishb** [comment]
Hi @rpkoller, this sounds great to me, I'd welcome a PR for these. Thanks for looking into this!

**Comment by aatishb** [comment]
Merged. Thanks @rpkoller.
